<?php

$title = $this->translate('Join');
$this->headMeta()->appendName('keywords', 'Signup, Join, Create');
$this->headMeta()->appendName('description', 'Signup, Join, Create');
$this->headTitle($this->escapeHtml($title));

$form = $this->form;
$form->setAttribute('action', $this->url('page.post'));
$form->prepare();

?>

<div class="container">
  <div class="row align-items-center justify-content-center">
    <div class="col-md-6 shadow-sm">
      <h2 class="pt-2 text-center">
        <span class="text-muted">
          <?= $this->translate('Create new account') ?>
        </span>
      </h2>
      <?= $this->form()->openTag($form) ?>

      <div class="mb-3">
        <?= $this->formLabel($form->get('firstname')); ?>
        <div class="input-group">
          <?= $this->formText($form->get('firstname')); ?>
        </div>
        <div class="text-danger">
          <?= $this->formElementErrors($form->get('firstname')); ?>
        </div>
      </div>

      <div class="mb-3">
        <?= $this->formLabel($form->get('surname')); ?>
        <div class="input-group">
          <?= $this->formText($form->get('surname')); ?>
        </div>
        <div class="text-danger">
          <?= $this->formElementErrors($form->get('surname')); ?>
        </div>
        <div class="mb-3">
          <?= $this->formLabel($form->get('password')); ?>
          <div class="input-group">
            <?= $this->formPassword($form->get('password')); ?>
          </div>
          <div class="text-danger">
            <?= $this->formElementErrors($form->get('password')); ?>
          </div>
        </div>

        <div class="mb-3">
          <?= $this->formLabel($form->get('confirm_password')); ?>
          <div class="input-group">
            <?= $this->formPassword($form->get('confirm_password')); ?>
          </div>
          <div class="text-danger">
            <?= $this->formElementErrors($form->get('confirm_password')); ?>
          </div>
        </div>

        <div class="mb-3">

          <?= $this->formSubmit($form->get('create_account')); ?>

        </div>
        <?= $this->form()->closeTag(); ?>
      </div>