<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.13.0/css/all.css')
    ->prependStylesheet('bootstrap/css/bootstrap.min.css')
    ->prependStylesheet('bootstrap/css/bootstrap-datetimepicker.min.css');
$this->inlineScript()
    ->prependFile('jquery/jguery-3.6.0.min.js')
    ->prependFile('bootstrap/js/bootstrap.min.js')
    ->prependFile('bootstrap/js/bootstrap-datetimepicker.min.js');


?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="https://getlaminas.org/images/favicon/favicon.ico" />

    <?= $this->headTitle('Práce - Formulář')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <style>
        body {
            padding-top: 70px;
        }

        .app {
            min-height: 100vh;
        }

        .app-footer {
            padding-bottom: 1em;
        }

        .mezzio-green,
        h2 a,
        h2 a:hover {
            color: #009655;
        }

        .navbar-brand {
            padding: 0;
        }

        .navbar-brand img {
            margin: -.5rem 0;
            filter: brightness(0) invert(1);
        }
    </style>

    <script>
        $(function() {
            $('#datetimepicker2').datetimepicker({
                locale: 'cs'

            });
        });
    </script>
</head>

<body class="app">
    <header class="app-header">

    </header>

    <div class="app-content">
        <main class="container">
            <?= $this->content ?>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container">
        </div>
    </footer>

    <?= $this->inlineScript() ?>
</body>

</html>