<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            Test\Handler\PostHandler::class => Test\Handler\PostHandlerFactory::class,
            Work\Handler\FormHandler::class => Work\Handler\FormHandlerFactory::class,
            Worker\Handler\FormHandler::class => Worker\Handler\FormHandlerFactory::class,
        ],
    ],
];
